### ISSUE TITLE
Pin actions? Or other security concerns.

### ISSUE THREAD

**Issue by wraithgar** [npm/template-oss#105]
Dependabot can keep actions up to date if we pinned them to a sha.  This issue is for discussing the pros and cons, and for other security items.

Pros:
 - in theory this is more secure because you can audit changes to actions.
 - dependabot can make PRs to keep shas up to date, and those PRs have a mechanism for reviewing the code. [links look like this](https://github.com/actions/setup-node/compare/04c56d2f954f1e4c69436aa54cfef261a018f458...1f8c6b94b26d0feae1e387ca63ccbdc44d27b561)

Cons:
 - our current actions are all either first party, or from google so this may be overkill.  If github actions themselves are compromised then this lockdown is the least of our worries.

We may also want to review the permissions level of each action, and explicitly limit them where appropriate  Most only need read access, which is less than the default access.

**Comment by ljharb** [comment]
Definitely permissions should be set.

I don’t see any value in pinning actions to a sha, as long as it’s a tagged version and a known maintainer.

**Comment by wraithgar** [comment]
We're currently not tagging a version, only a major.

**Comment by ljharb** [comment]
“v2” counts as a tagged (non-semver) version to me :-)

**Comment by wraithgar** [comment]
dependabot can't keep our templated yaml source files up to date so this is untenable.  We added no-fund/no-audit/no-scripts to the existing actions where it made sense.
