### ISSUE TITLE
[BUG] release version is tied to PR, not to commit

### ISSUE THREAD

**Issue by wraithgar** [npm/template-oss#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See https://github.com/npm/cli/pull/6609.  Arborist got a semver minor due to a commit that didn't affect it, but was part of a PR that did affect it.

### Expected Behavior

Arborist should have gotten a semver minor.

**Comment by lukekarrys** [comment]
Dug into this finally and found it is due to behavior in `release-please`. I opened a PR to fix this https://github.com/googleapis/release-please/pull/2141. Hopefully that will land and once #334 lands here we can update release-please to get the fix.

**Comment by lukekarrys** [comment]
This is fixed now after https://github.com/googleapis/release-please/pull/2141 landed in `release-please@16.3.1` and #334 has been merged.
