### ISSUE TITLE
Branch protection settings dont work for wildcards

### ISSUE THREAD

**Issue by lukekarrys** [npm/template-oss#329]
Our release branches follow the pattern `release/v*` but this doesn't work with Probot + `.github/settings.yml`. Ref: https://github.com/repository-settings/app/issues/227#issuecomment-619240005

Possible solutions:
- generate branch protection rules for possible release branch explicitly `release/v[1-30]`. This would clutter the web UI for branch protections.
- manually configure branch protections for each actual release branch. Tradeoffs: error prone and possible to forget or misconfigure some settings
- Require configuration in template-oss for each required release branch. Less error prone, but still possible to forget.

**Comment by wraithgar** [comment]
The third option seems like the one that leaves us open to configuring what versions we backport in template-oss itself.

**Comment by lukekarrys** [comment]
A version will only be back ported if template oss is installed on that branch. But we still want to protect those branches regardless, and branch protections are only created from the settings file on the default branch.

I came up with a solution in the linked PR which uses info from the git remote which I think works pretty well.
