### ISSUE TITLE
[bug] `isReleaseBranch` check fails for PR to release branches

### ISSUE THREAD

**Issue by lukekarrys** [npm/template-oss#338]
a release branch is checked based on matching the pattern `release/v*`. making a PR to a release branch wont match that pattern so that check will be false which will reset some templated files to the incorrect state.

Possible solutions:
- [x] make `isReleaseBranch` config only that needs to be set manually per branch
- [ ] make branch pattern match PR branches and require PRs to release branches be named according to that pattern (eg `release/v9-update-config`)

**Comment by rotu** [comment]
Is this issue responsible for:
```
​FAIL ​ test/check/dogfood.js
✖ should be equivalent strictly
...
  +  Object {
  +    "title": "The module file package.json needs to be updated:",
  +    "body": Array [
  +      String(
  +        workspace\\test-workspace\\package.json
  +        ========================================
  +        "repository.url" is "https://github.com/npm/template-oss.git", expected
"https://github.com/rotu/npm-template-oss.git"
  +      ),
  +    ],
  +    "solution": "npx template-oss-apply --force",
  +  },
```

**Comment by lukekarrys** [comment]
@rotu that is due to the autodetection of the `origin` by git. If you've forked the repo make sure that `npm/template-oss` is the `origin` and the remote url for your fork is named something different (eg `fork`):

```
❯ git remotes
fork	git@github.com:lukekarrys/template-oss.git (fetch)
fork	git@github.com:lukekarrys/template-oss.git (push)
origin	git@github.com:npm/template-oss.git (fetch)
origin	git@github.com:npm/template-oss.git (push)
```
