### ISSUE TITLE
[BUG] tap-testdir-* is not gitignored

### ISSUE THREAD

**Issue by rotu** [npm/template-oss#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running npm/cli tests on windows, I was seeing many files churn in and out of the source control files list.

These ephemeral test files slow down the IDE considerably and can make it hard to see what actually changed.

![image](https://github.com/npm/template-oss/assets/119948/a02423b6-c498-4153-82cd-d2117d91393e)
 

### Expected Behavior

Files created by tap tests should either be:
1. ignored by gitignore.
2. created outside the git working tree

### Steps To Reproduce

1. In VSCode on Windows, clone https://github.com/npm/cli
2. Open the Source Control pane
3. Run `npm test`

### Environment

- npm: 9.6.7
- Node: 18.17.1
- OS: Windows 11
- platform: AMD64 Desktop

**Comment by rotu** [comment]
Note this seems to happen in GitHub codespaces as well.

**Comment by lukekarrys** [comment]
One reason that those aren't currently ignored is that they are ephemeral and should be deleted by the end of `npm test` in CI. We then have `git status` checks which would fail if those files are not properly cleaned up. I'm not currently sure what situation is testing against though. It might be safe to assume those files are always cleaned up and if they are not then it's a problem with our testing framework

And you make a good point about making it difficult to see what has changed and causing contributor friction. I'd be in favor of this change.

@rotu would you like to make a PR for this?

**Comment by rotu** [comment]
I gave it a shot in #350.

Note that terminating tests with ctrl-c also results in these files not getting cleaned up, which compounds the problem (not sure if on purpose or due to https://github.com/npm/cli/issues/6766).

**Comment by wraithgar** [comment]
In my current setup I do rely on those files showing up in `git status` when I want to tell tap to keep fixtures, so I can find them easily.  It's not a deal breaker but it'll be mildly annoying to have to try to hunt them down if git is ignoring them.

**Comment by rotu** [comment]
> In my current setup I do rely on those files showing up in `git status` when I want to tell tap to keep fixtures, so I can find them easily. It's not a deal breaker but it'll be mildly annoying to have to try to hunt them down if git is ignoring them.

```shell
git status --ignored ./test
```

It does seem odd to me that the snapshots are centralized under a `tap-snapshots/` folder, but the fixtures are not under some `tap-testdir/` root. I would feel more comfortable avoiding globs in `.gitignore` where possible, and I would think any tooling that watches the file system would prefer it too!

**Comment by wraithgar** [comment]
Yeah I'll probably have to finally commig `--ignored` to memory. This is not a deal breaker to be sure.


As to where tap puts things, that's something to bring up in the tapjs repos. I know Isaac is hard at work on the next major version right now.
