### ISSUE TITLE
package scripts should use `upstream`, not `origin`, to set repository.url from git

### ISSUE THREAD

**Issue by rotu** [npm/template-oss#363]
The repository URLs are based on assuming that `origin` is the authoritative url and updates `package.json` based on this. In the case of this repo, it causes tests to fail locally.

This should be expecting `origin` to be the default branch to push/pull and `upstream` to be the authoritative repo because:

- This is the setup recommended by GitHub https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork
- This is what happens if you clone a repo "for contributing to the upstream project" in GitHub desktop
- This is what happens if you clone a repo in VSCode, try to push to that repo, and choose to create a fork when it prompts you to.

Per @lukekarrys in https://github.com/npm/template-oss/issues/338#issuecomment-1719980875
> @rotu that is due to the autodetection of the `origin` by git. If you've forked the repo make sure that `npm/template-oss` is the `origin` and the remote url for your fork is named something different (eg `fork`):
> 
> ```
> ❯ git remotes
> fork	git@github.com:lukekarrys/template-oss.git (fetch)
> fork	git@github.com:lukekarrys/template-oss.git (push)
> origin	git@github.com:npm/template-oss.git (fetch)
> origin	git@github.com:npm/template-oss.git (push)
> ```

**Comment by lukekarrys** [comment]
This tool is mainly designed to run in *other* repos where `origin` is the default remote. 

Probably the best thing to do here is skip that check when specifically in this `template-oss` repo like we do with the version check.

Alternatively we could do the same thing we do in `lib/content/_job.yml` and hardcode a `repository_owner` type variable (which should probably be moved to `lib/content/index.js) and only apply the package.json git url if the current remote matches.

**Comment by rotu** [comment]
This issue does not just impact contributing to the `template-oss` repo. In `npm-cli`,

`npm run lint`


```
> npm@10.1.0 lint
> eslint "**/*.js"


> npm@10.1.0 postlint
> template-oss-check


Some problems were detected:

-------------------------------------------------------------------

The module file package.json needs to be updated:

  package.json
  ========================================
  "repository.url" is "https://github.com/npm/cli.git", expected "https://github.com/rotu/cli.git"

To correct it: npx template-oss-apply --force

-------------------------------------------------------------------

The module file package.json needs to be updated:

  docs/package.json
  ========================================
  "repository.url" is "https://github.com/npm/cli.git", expected "https://github.com/rotu/cli.git"

To correct it: npx template-oss-apply --force

-------------------------------------------------------------------
...
```
and it goes on like this for several more packages.
