### ISSUE TITLE
Make release-please rebuild PR for chore commits

### ISSUE THREAD

**Issue by lukekarrys** [npm/template-oss#378]
Problem statement: release-please will only rebuild a release PR when the body of the PR changes.

Current solution: run a workflow that forces the PR to be rebuilt by changing the PR body.

Problems with current solution: Requires manual work.

New proposed solution: We append Last commit: $SHA to the bottom of every PR body (and therefore changelog). This will have the effect of rebuilding the PR for every commit without including changelog entries for chore commits. (edited)

**Comment by wraithgar** [comment]
We should stop omitting `chore` from the changelog, and put it in a `<details>` block so it doesn't take up real estate by default.  We can continue using `chore` for now but will also add a scope to our chore commits so we can start to see if we eventually want a new section (like `build` or `tests`).

**Comment by wraithgar** [comment]
Current hard problem: Naming the changelog header for this section.
