### ISSUE TITLE
[spike] node-workspaces plugin for release-please

### ISSUE THREAD

**Issue by lukekarrys** [npm/template-oss#59]
https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#node-workspace

> The node-workspace plugin builds a graph of local node packages configured in release-please-config.json and the dependency relationships between them. It looks at what packages were updated by release-please and updates their reference in other packages' dependencies lists.

**Comment by wraithgar** [comment]
this was more complicated than we needed, the release-please action for workspaces does this for the cli now and we can iterate as we need.
